# Generated by Django 3.1.7 on 2021-04-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20210420_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='character',
            new_name='characters',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='prop',
            new_name='props',
        ),
        migrations.RemoveField(
            model_name='actionevent',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='actionevent',
            name='verb',
        ),
        migrations.RemoveField(
            model_name='event',
            name='actor_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='actor_start',
        ),
        migrations.AddField(
            model_name='entity',
            name='refers_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.entity'),
        ),
    ]
